### ISSUE TITLE
shasum must be installed & on PATH. Aborting.

### ISSUE THREAD

**Issue by longzifan** [apache/fluo-uno#256] opened 2020-09-28 05:04 UTC
According to the document
./uno fetch accumulo
A header error occurred

**Comment by ctubbsii** [comment] 2020-09-28 05:28
@longzifan Your description above is lacking detail. If I understand your intention correctly, you are trying to report the error that occurs when you do not have `shasum` installed and available on your system's execution `PATH`. That error is not a bug. It is expected if you don't have `shasum`, because that is a prerequisite for the tool.

I'm going to close this issue because it's not a bug and is expected behavior. If I have misunderstood your intent, please comment with more details to explain what you are trying to report.

**Closed by ctubbsii** 2020-09-28 05:28 UTC
Labels: invalid

**Comment by longzifan** [comment] 2020-09-28 06:09
i want know，how  get shasum。Because I performed the installation according to the documentation。

Uno requires the following software to be installed on your machine.

Java - JDK 8 is required for running Fluo.
wget - Needed for fetch command to download tarballs.
Maven - Only needed if fetch command builds tarball from local repo.

The above conditions are met localhost
Execute to
./bin/uno fetch accumulo
throw out shasum must be installed & on PATH. Aborting.



Looking forward to your answers

**Comment by milleruntime** [comment] 2020-09-28 13:09
The "shasum" executable scripts should be installed using the package manager of your Linux OS.  For example, if using CentOS you may have to run "yum install -y perl-Digest-SHA" to install the perl scripts.  Ubuntu systems should include it with "apt install perl"

**Comment by ctubbsii** [comment] 2020-09-28 19:38
On Fedora, the command would be: `sudo dnf install perl-Digest-SHA` (similar to the CentOS command, but with `dnf` instead of `yum`). I never recommend adding `-y` to these commands, though, because it's good to manually approve any prompts after reading them thoroughly rather than automatically approve them.

Like Ubuntu, this should be installed by default if you have `perl` installed on Fedora (specifically, `perl-CPAN`). In most installations, `perl` is installed already (either by default, or as part of the "Linux Server Base" (lsb) standard server install), so it's probably not necessary to explicitly state how to install it in the instructions. I think the error message is sufficient for most cases.

However, I have noticed that over time, particularly on VMs, `perl` is no longer included in some Linux distros' default install. For that reason, we may wish to switch our scripts to use `openssl` or another tool that is more likely to be installed. I don't think we're there yet, but perhaps something to consider in future. I'd be willing to accept a pull request to change it, if somebody felt it was necessary.
